version: '3.9'

services:
  mssql:
    image: mcr.microsoft.com/mssql/server:latest
    container_name: mssql_db
    environment:
      SA_PASSWORD: Fenome1Password!
      ACCEPT_EULA: Y
      MSSQL_PID: Developer
    ports:
      - "1433:1433"
    volumes:
      - mssql_data:/var/opt/mssql
volumes:
  mssql_data:
